# This workflow will do a clean install of node dependencies, build the libby example
name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  example:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:cli
      - run: npm run build:ci
